testnet:
  client:
    name: ${CLIENT_NAME}
grpc:
  client:
    GLOBAL:
      negotiation-type: tls
      security:
        authority-override: localhost
        trust-cert-collection: selfsigned.crt
      enable-keep-alive: true
      address: ${GRPC_ADDRESS}
