server:
  port: -1
logging:
  level:
    root: info
    logging:
      com.baomidou.mybatisplus.core.mapper: DEBUG
spring:
  application:
    name: testnet-executor
  profiles:
    active: '@profile.name@'
#
liteflow:
  rule-source-ext-data-map:
    applicationName: testnet-client
    #是否开启SQL日志
    sqlLogEnabled: false
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    pollingEnabled: true
    pollingIntervalSeconds: 10
    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    chainTableName: lite_flow_chain
    chainApplicationNameField: application_name
    chainNameField: chain_name
    elDataField: el_data
    chainEnableField: enable
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: lite_flow_script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: script_language
    scriptEnableField: enable
  print-banner: false
  parse-mode: PARSE_ONE_ON_FIRST_EXEC
testnet:
  client:
    name: testnet-client
    version: v1.0
  result:
    path: /tmp/