# 修复职位提示SQL注入
INSERT INTO `sys_table_white_list` (`id`, `table_name`, `field_name`, `status`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('1818532411849027585', 'sys_position', 'name,id', '1', 'admin', '2024-07-31 14:21:28', NULL, NULL);
ALTER TABLE `lite_flow_sub_task` MODIFY COLUMN `config` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '配置';
ALTER TABLE `asset_web` MODIFY COLUMN `tech` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '技术框架';
# 优化nuclei
UPDATE `lite_flow_script` set install_command= 'export GOPROXY=https://goproxy.cn,direct\ngo install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest\n#下载poc\nnuclei' WHERE `id` = '1781286631852261378';
# naabu
INSERT INTO `lite_flow_chain` VALUES ('1818670068314804225', 'admin', '2024-05-01 00:00:00', 'admin', '2024-05-01 00:00:00', 'A01', 'Naabu C段端口扫描', 'THEN(naabu)', 'testnet-client', 1, 'ip', 'ant-design:instagram-outlined', 'command: \'naabu -no-stdin -c 200 -json -top-ports 100 -host %s/24 -o %s\'', 'ipOrSubDomainToPortProcessor', 2);
# oneforall
UPDATE `lite_flow_script` set install_command= 'cd /testnet-client/tools\nif [ -z \"$(ls -A OneForAll)\" ]; then\n    rm -rf OneForAll\nfi\ngit clone --depth 1 --branch master https://github.com/shmilylty/OneForAll.git\ncd OneForAll\npip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/' where `id` = '1773680693413994497';
UPDATE `lite_flow_script` set version_check_command= 'python3 /testnet-client/tools/OneForAll/oneforall.py version 2>&1 | grep -oP ''v\d+\.\d+\.\d+''' where `id` = '1773680693413994497';
# nmap
UPDATE `lite_flow_script` set version_check_command= 'nmap --version 2>&1 | grep -oP ''Nmap version \K\d+\.\d+''' where `id` = '1790213876943757314';

INSERT INTO `lite_flow_chain` VALUES ('1820100181514387457', 'admin', '2024-05-01 00:00:00', 'admin', '2024-05-01 00:00:00', 'A01', '搜索引擎批量导入', 'THEN(search_engine)', 'testnet-client', 1, NULL, NULL, NULL, 'searchEngineImportProcessor', 1);
INSERT INTO `lite_flow_script` VALUES ('1820078397037608961', 'admin', '2024-05-01 00:00:00', 'admin', '2024-05-01 00:00:00', 'A01', '空间引擎一键导入', 'script', 'import com.alibaba.fastjson.JSONObject;\nimport com.yomahub.liteflow.script.ScriptExecuteWrap;\nimport com.yomahub.liteflow.script.body.JaninoCommonScriptBody;\nimport com.yomahub.liteflow.spi.holder.ContextAwareHolder;\nimport testnet.client.service.ILiteFlowMessageSendService;\nimport testnet.common.dto.SearchEngineImportDTO;\nimport testnet.common.entity.liteflow.TaskExecuteMessage;\n\n\npublic class SearchEngine implements JaninoCommonScriptBody {\n    public Void body(ScriptExecuteWrap wrap) {\n        TaskExecuteMessage taskExecuteMessage = (TaskExecuteMessage) wrap.cmp.getRequestData();\n        try {\n            ILiteFlowMessageSendService sendService = (ILiteFlowMessageSendService) ContextAwareHolder.loadContextAware().getBean(ILiteFlowMessageSendService.class);\n            sendService.setTaskId(taskExecuteMessage.getTaskId());\n            JSONObject instanceParams = JSONObject.parseObject(taskExecuteMessage.getTaskParams());\n            SearchEngineImportDTO searchEngineImportDTO = new SearchEngineImportDTO();\n            searchEngineImportDTO.setCurrentPage(instanceParams.getInteger(\"currentPage\"));\n            sendService.sendResult(searchEngineImportDTO);\n        } catch (Exception e) {\n            throw new RuntimeException(e);\n        }\n        return null;\n    }\n}', 'java', 1, 'testnet-client', 'search_engine', 'OTHERS', NULL, NULL, 0, NULL);
